<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZuHItiU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZuHItiU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZuHItiU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZuHItiU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZuHItiU\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZuHItiU',
    'container.build_id' => 'b6f57593',
    'container.build_time' => 1749628140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZuHItiU');
