<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6arpkxK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6arpkxK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6arpkxK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6arpkxK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6arpkxK\App_KernelDevDebugContainer([
    'container.build_hash' => '6arpkxK',
    'container.build_id' => 'c17f14be',
    'container.build_time' => 1750020510,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6arpkxK');
