<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5jAfxtg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5jAfxtg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5jAfxtg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5jAfxtg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5jAfxtg\App_KernelDevDebugContainer([
    'container.build_hash' => '5jAfxtg',
    'container.build_id' => 'ac41120e',
    'container.build_time' => 1749981186,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5jAfxtg');
